import { app, BrowserWindow, dialog, ipcMain, shell } from 'electron'
import path from 'node:path'
import fs from 'node:fs/promises'
import { watch as watchFiles, type FSWatcher } from 'node:fs'
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import type { AppState, Bot, ChatRequest, ConsultationRequest, LedgerNote, PullProgress, WorkflowManifest, WorkflowStartRequest, WorkspaceStatus } from '../src/types'
import { approveWorkflow, listWorkflows, retryWorkflowTask, setManifestCancelled, setManifestPaused, startWorkflow } from './orchestrator.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
if (process.env.SKEPO_CAPTURE_PATH) app.disableHardwareAcceleration()
const activeRequests = new Map<string, AbortController>()
const workspaceWatchers = new Map<string, FSWatcher>()

const defaultState: AppState = {
  bots: [],
  conversations: [],
  settings: {
    ollamaUrl: 'http://127.0.0.1:11434',
    theme: 'dark',
    sendOnEnter: true,
    compactMode: false,
    workspacePath: '',
    sharedMemoryEnabled: true,
    maxSharedNotes: 4,
  },
}

const stopWords = new Set(['the','and','that','this','with','from','have','will','your','you','for','are','was','were','what','when','where','which','into','about','then','than','but','not','can','could','should','would','our','out','all','any','how'])

function requireWorkspace(rawPath: string) {
  const resolved = path.resolve(rawPath.trim())
  if (!rawPath.trim() || !path.isAbsolute(resolved) || resolved === path.parse(resolved).root) throw new Error('Choose a folder, not an entire drive root.')
  return resolved
}

function safeName(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48) || 'bot'
}

function keywordsFor(value: string) {
  const counts = new Map<string, number>()
  for (const token of value.toLowerCase().match(/[a-z0-9][a-z0-9._-]{2,}/g) ?? []) {
    if (stopWords.has(token)) continue
    counts.set(token, (counts.get(token) ?? 0) + 1)
  }
  return [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 14).map(([token]) => token)
}

function compactText(value: string, limit = 1400) {
  const clean = value.replace(/\r/g, '').replace(/\n{3,}/g, '\n\n').trim()
  return clean.length > limit ? `${clean.slice(0, limit).trimEnd()}…` : clean
}

function ledgerRoot(workspace: string) {
  const resolved = requireWorkspace(workspace)
  const current = path.join(resolved, '.skepo-ledger')
  const legacy = path.join(resolved, '.localbot-ledger')
  return existsSync(current) || !existsSync(legacy) ? current : legacy
}
function ledgerIndexPath(workspace: string) { return path.join(ledgerRoot(workspace), 'index.json') }

async function readLedgerIndex(workspace: string): Promise<LedgerNote[]> {
  try {
    const parsed = JSON.parse(await fs.readFile(ledgerIndexPath(workspace), 'utf8')) as { notes?: LedgerNote[] }
    return Array.isArray(parsed.notes) ? parsed.notes : []
  } catch { return [] }
}

async function writeLedgerIndex(workspace: string, notes: LedgerNote[]) {
  const destination = ledgerIndexPath(workspace)
  const temp = `${destination}.tmp`
  await fs.mkdir(path.dirname(destination), { recursive: true })
  await fs.writeFile(temp, JSON.stringify({ version: 1, updatedAt: Date.now(), notes }, null, 2), 'utf8')
  await fs.rename(temp, destination)
  const recent = [...notes].sort((a, b) => b.createdAt - a.createdAt).slice(0, 100)
  const markdown = `# Shared Ledger Index\n\nThis file is generated by Skepo. It is intentionally readable, portable, and Git-friendly.\n\n${recent.map(note => `- [${note.title}](${note.relativePath.replace(/\\/g, '/')}) — **${note.botName}** · ${new Date(note.createdAt).toISOString()} · ${note.keywords.slice(0, 5).map(k => `\`${k}\``).join(' ')}`).join('\n')}\n`
  await fs.writeFile(path.join(ledgerRoot(workspace), 'INDEX.md'), markdown, 'utf8')
}

async function initializeWorkspace(workspace: string, bots: Bot[] = []) {
  const root = ledgerRoot(workspace)
  await fs.mkdir(path.join(root, 'bots'), { recursive: true })
  await fs.mkdir(path.join(root, 'handoffs'), { recursive: true })
  await fs.mkdir(path.join(root, 'shared'), { recursive: true })
  await fs.mkdir(path.join(root, 'sessions'), { recursive: true })
  const readme = `# Skepo Shared Ledger\n\nThis folder is a file-native memory bus for local AI agents. Every completed task becomes a compact Markdown work card. Agents receive only a few relevant cards, selected locally by transparent keyword scoring—no vector database and no hidden cloud index.\n\n## Structure\n\n- \`INDEX.md\` — human-readable activity index\n- \`bots/<bot>/CURRENT.md\` — each agent's recent working state\n- \`bots/<bot>/journal/\` — append-only work cards\n- \`handoffs/\` — explicit agent-to-agent consultation records\n- \`index.json\` — rebuildable local lookup metadata\n\nThe Markdown files are the source of truth. You can inspect, edit, back up, or commit this directory to a private Git repository.\n`
  try { await fs.access(path.join(root, 'README.md')) } catch { await fs.writeFile(path.join(root, 'README.md'), readme, 'utf8') }
  for (const bot of bots) await fs.mkdir(path.join(root, 'bots', `${safeName(bot.name)}-${bot.id.slice(0, 6)}`, 'journal'), { recursive: true })
  const notes = await readLedgerIndex(workspace)
  if (notes.length === 0) await writeLedgerIndex(workspace, [])
}

async function workspaceStatus(workspace: string): Promise<WorkspaceStatus> {
  if (!workspace.trim()) return { initialized: false, path: '', noteCount: 0, botCount: 0, recentNotes: [] }
  try {
    const notes = await readLedgerIndex(workspace)
    await fs.access(path.join(ledgerRoot(workspace), 'README.md'))
    return { initialized: true, path: requireWorkspace(workspace), noteCount: notes.length, botCount: new Set(notes.map(n => n.botId)).size, recentNotes: [...notes].sort((a,b) => b.createdAt - a.createdAt).slice(0, 30) }
  } catch (error) {
    return { initialized: false, path: requireWorkspace(workspace), noteCount: 0, botCount: 0, recentNotes: [], error: error instanceof Error ? error.message : String(error) }
  }
}

async function recordWork(workspace: string, bot: Bot, conversationId: string, title: string, request: string, outcome: string, kind: LedgerNote['kind'] = 'work', counterpart?: Bot) {
  await initializeWorkspace(workspace, [bot, ...(counterpart ? [counterpart] : [])])
  const now = Date.now()
  const id = `${now}-${Math.random().toString(36).slice(2, 8)}`
  const botFolder = `${safeName(bot.name)}-${bot.id.slice(0, 6)}`
  const relativePath = kind === 'handoff'
    ? path.join('handoffs', `${new Date(now).toISOString().replace(/[:.]/g, '-')}-${safeName(title)}.md`)
    : path.join('bots', botFolder, 'journal', `${new Date(now).toISOString().replace(/[:.]/g, '-')}-${safeName(title)}.md`)
  const note: LedgerNote = {
    id, botId: bot.id, botName: bot.name, conversationId, title: compactText(title, 90), request: compactText(request, 900), outcome: compactText(outcome, 1800),
    keywords: keywordsFor(`${title} ${request} ${outcome}`), createdAt: now, relativePath, kind,
    fromBotName: kind === 'handoff' ? bot.name : undefined, toBotName: kind === 'handoff' ? counterpart?.name : undefined,
  }
  const markdown = `---\nid: ${id}\ntype: ${kind}\nbot: ${JSON.stringify(bot.name)}\nbot_id: ${bot.id}\nconversation_id: ${conversationId}\ncreated: ${new Date(now).toISOString()}\nkeywords: [${note.keywords.join(', ')}]\n---\n\n# ${note.title}\n\n## Request\n\n${note.request}\n\n## Outcome\n\n${note.outcome}\n\n## Continuation\n\nFuture bots should verify assumptions against the current files and continue from the outcome above instead of repeating the full conversation.\n`
  const fullPath = path.join(ledgerRoot(workspace), relativePath)
  await fs.mkdir(path.dirname(fullPath), { recursive: true })
  await fs.writeFile(fullPath, markdown, 'utf8')
  const notes = [...await readLedgerIndex(workspace), note]
  await writeLedgerIndex(workspace, notes)
  const botNotes = notes.filter(n => n.botId === bot.id).sort((a,b) => b.createdAt - a.createdAt).slice(0, 12)
  const current = `# ${bot.name} — Current State\n\nUpdated ${new Date().toISOString()}\n\n${botNotes.map(n => `## ${n.title}\n\n- Request: ${compactText(n.request, 220)}\n- Outcome: ${compactText(n.outcome, 420)}\n- Card: [${n.relativePath.replace(/\\/g, '/').split('/').at(-1)}](../../${n.relativePath.replace(/\\/g, '/')})\n`).join('\n')}\n`
  await fs.writeFile(path.join(ledgerRoot(workspace), 'bots', botFolder, 'CURRENT.md'), current, 'utf8')
  return note
}

async function relevantNotes(workspace: string, query: string, botId: string, limit: number) {
  const queryTerms = new Set(keywordsFor(query))
  const now = Date.now()
  return (await readLedgerIndex(workspace)).map(note => {
    let score = note.keywords.reduce((sum, word) => sum + (queryTerms.has(word) ? 5 : 0), 0)
    const haystack = `${note.title} ${note.request}`.toLowerCase()
    for (const word of queryTerms) if (haystack.includes(word)) score += 2
    if (note.botId !== botId) score += 1.25
    score += Math.max(0, 1 - (now - note.createdAt) / 604_800_000)
    return { note, score }
  }).filter(item => item.score > 1).sort((a,b) => b.score - a.score).slice(0, Math.max(0, Math.min(limit, 8))).map(item => item.note)
}

function cleanBaseUrl(raw: string) {
  const url = raw.trim().replace(/\/+$/, '')
  if (!/^https?:\/\//i.test(url)) throw new Error('Ollama URL must start with http:// or https://')
  return url
}

async function fetchOllama(url: string, init?: RequestInit) {
  try {
    return await fetch(url, init)
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    throw new Error(`Cannot reach Ollama. Make sure Ollama is running. (${message})`)
  }
}

async function runModel(bot: Bot, messages: { role: string; content: string }[], rawUrl: string, timeoutMs = 180_000) {
  const response = await fetchOllama(`${cleanBaseUrl(rawUrl)}/api/chat`, {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, signal: AbortSignal.timeout(timeoutMs),
    body: JSON.stringify({ model: bot.model, stream: false, messages, options: { temperature: bot.temperature, top_p: bot.topP, num_ctx: bot.contextLength } }),
  })
  if (!response.ok) throw new Error(await response.text() || `Ollama returned HTTP ${response.status}`)
  const data = await response.json() as { message?: { content?: string }; error?: string; prompt_eval_count?: number; eval_count?: number }
  if (data.error) throw new Error(data.error)
  return { content: data.message?.content?.trim() ?? '', tokens: (data.prompt_eval_count ?? 0) + (data.eval_count ?? 0) }
}

async function syncWorkspaceBots(workspace: string, bots: Bot[]) {
  const destination = path.join(ledgerRoot(workspace), 'bots.json')
  const temp = `${destination}.tmp`
  const portable = bots.map(({ id, name, description, model, systemPrompt, avatarColor, temperature, topP, contextLength, createdAt, updatedAt }) => ({ id, name, description, model, systemPrompt, avatarColor, temperature, topP, contextLength, createdAt, updatedAt }))
  await fs.mkdir(path.dirname(destination), { recursive: true })
  await fs.writeFile(temp, JSON.stringify({ version: 1, updatedAt: Date.now(), bots: portable }, null, 2), 'utf8')
  await fs.rename(temp, destination)
  await fs.writeFile(path.join(ledgerRoot(workspace), 'workspace.json'), JSON.stringify({ version: 1, name: path.basename(requireWorkspace(workspace)), updatedAt: Date.now(), protocol: 'skepo-ledger-v1' }, null, 2), 'utf8')
}

function watchWorkspace(workspace: string, sender: Electron.WebContents) {
  const resolved = requireWorkspace(workspace)
  workspaceWatchers.get(resolved)?.close()
  let timer: NodeJS.Timeout | undefined
  try {
    const watcher = watchFiles(ledgerRoot(resolved), { recursive: true }, (_event, filename) => {
      if (!filename || filename.endsWith('.tmp')) return
      if (timer) clearTimeout(timer)
      timer = setTimeout(() => { if (!sender.isDestroyed()) sender.send('workflow:event', { type: 'workspace-changed', path: resolved }) }, 250)
    })
    workspaceWatchers.set(resolved, watcher)
  } catch { /* The folder may not exist until initialization completes. */ }
}

function createWorkflowEmitter(sender: Electron.WebContents, request: WorkflowStartRequest) {
  let recorded = false
  return (manifest: WorkflowManifest) => {
    if (!sender.isDestroyed()) sender.send('workflow:event', { type: 'updated', manifest })
    if (!recorded && manifest.status === 'completed' && manifest.finalOutput) {
      recorded = true
      const reviewer = request.bots.find(bot => bot.id === manifest.reviewerBotId)
      if (reviewer) void recordWork(request.workspacePath, reviewer, manifest.sessionId, `Workflow: ${manifest.goal}`, manifest.goal, manifest.finalOutput).catch(() => undefined)
    }
  }
}

function statePath() {
  return path.join(app.getPath('userData'), 'skepo-state.json')
}

async function readState(): Promise<AppState> {
  const candidates = [
    statePath(),
    path.join(app.getPath('userData'), 'localbot-state.json'),
    path.join(app.getPath('appData'), 'LocalBot', 'localbot-state.json'),
  ]
  for (const candidate of candidates) {
    try {
      const value = JSON.parse(await fs.readFile(candidate, 'utf8')) as Partial<AppState>
      const state = {
        bots: Array.isArray(value.bots) ? value.bots : [],
        conversations: Array.isArray(value.conversations) ? value.conversations : [],
        settings: { ...defaultState.settings, ...value.settings },
      }
      if (candidate !== statePath()) await writeState(state)
      return state
    } catch { /* Try the next current or legacy state location. */ }
  }
  return structuredClone(defaultState)
}

async function writeState(state: AppState) {
  const destination = statePath()
  const temp = `${destination}.tmp`
  await fs.mkdir(path.dirname(destination), { recursive: true })
  await fs.writeFile(temp, JSON.stringify(state, null, 2), 'utf8')
  await fs.rename(temp, destination)
}

function registerIpc() {
  ipcMain.handle('state:load', readState)
  ipcMain.handle('state:save', (_event, state: AppState) => writeState(state))

  ipcMain.handle('ollama:check', async (_event, rawUrl: string) => {
    try {
      const response = await fetchOllama(`${cleanBaseUrl(rawUrl)}/api/version`, { signal: AbortSignal.timeout(4000) })
      if (!response.ok) throw new Error(`HTTP ${response.status}`)
      const data = (await response.json()) as { version?: string }
      return { ok: true, version: data.version }
    } catch (error) {
      return { ok: false, error: error instanceof Error ? error.message : String(error) }
    }
  })

  ipcMain.handle('ollama:models', async (_event, rawUrl: string) => {
    const response = await fetchOllama(`${cleanBaseUrl(rawUrl)}/api/tags`, { signal: AbortSignal.timeout(7000) })
    if (!response.ok) throw new Error(`Ollama returned HTTP ${response.status}`)
    const data = (await response.json()) as { models?: unknown[] }
    return data.models ?? []
  })

  ipcMain.handle('ollama:chat', async (event, request: ChatRequest, rawUrl: string) => {
    const controller = new AbortController()
    activeRequests.get(request.requestId)?.abort()
    activeRequests.set(request.requestId, controller)
    const startedAt = performance.now()
    let evalCount = 0
    let evalDuration = 0
    try {
      const messages = request.bot.systemPrompt.trim()
        ? [{ role: 'system', content: request.bot.systemPrompt.trim() }, ...request.messages]
        : request.messages
      const response = await fetchOllama(`${cleanBaseUrl(rawUrl)}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: request.bot.model,
          messages,
          stream: true,
          options: {
            temperature: request.bot.temperature,
            top_p: request.bot.topP,
            num_ctx: request.bot.contextLength,
          },
        }),
        signal: controller.signal,
      })
      if (!response.ok || !response.body) {
        const detail = await response.text()
        throw new Error(detail || `Ollama returned HTTP ${response.status}`)
      }
      const reader = response.body.getReader()
      const decoder = new TextDecoder()
      let buffer = ''
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        buffer += decoder.decode(value, { stream: true })
        const lines = buffer.split('\n')
        buffer = lines.pop() ?? ''
        for (const line of lines) {
          if (!line.trim()) continue
          const packet = JSON.parse(line) as {
            message?: { content?: string }
            error?: string
            eval_count?: number
            eval_duration?: number
          }
          if (packet.error) throw new Error(packet.error)
          if (packet.message?.content) {
            event.sender.send('ollama:chat-event', { type: 'chunk', requestId: request.requestId, content: packet.message.content })
          }
          evalCount = packet.eval_count ?? evalCount
          evalDuration = packet.eval_duration ?? evalDuration
        }
      }
      const tokensPerSecond = evalDuration > 0 ? evalCount / (evalDuration / 1e9) : undefined
      event.sender.send('ollama:chat-event', {
        type: 'done',
        requestId: request.requestId,
        stats: { tokensPerSecond, totalDuration: performance.now() - startedAt },
      })
    } catch (error) {
      if (!controller.signal.aborted) {
        event.sender.send('ollama:chat-event', {
          type: 'error', requestId: request.requestId, error: error instanceof Error ? error.message : String(error),
        })
      } else {
        event.sender.send('ollama:chat-event', { type: 'done', requestId: request.requestId })
      }
    } finally {
      activeRequests.delete(request.requestId)
    }
  })

  ipcMain.handle('ollama:stop', (_event, requestId: string) => activeRequests.get(requestId)?.abort())
  ipcMain.handle('ollama:pull', async (event, name: string, rawUrl: string) => {
    const response = await fetchOllama(`${cleanBaseUrl(rawUrl)}/api/pull`, {
      method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, stream: true }),
    })
    if (!response.ok || !response.body) throw new Error(await response.text() || `HTTP ${response.status}`)
    const reader = response.body.getReader()
    const decoder = new TextDecoder()
    let buffer = ''
    while (true) {
      const { done, value } = await reader.read()
      if (done) break
      buffer += decoder.decode(value, { stream: true })
      const lines = buffer.split('\n')
      buffer = lines.pop() ?? ''
      for (const line of lines) {
        if (!line.trim()) continue
        const progress = JSON.parse(line) as PullProgress & { error?: string }
        if (progress.error) throw new Error(progress.error)
        event.sender.send('ollama:pull-progress', progress)
      }
    }
  })
  ipcMain.handle('ollama:delete', async (_event, name: string, rawUrl: string) => {
    const response = await fetchOllama(`${cleanBaseUrl(rawUrl)}/api/delete`, {
      method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }),
    })
    if (!response.ok) throw new Error(await response.text() || `HTTP ${response.status}`)
  })

  ipcMain.handle('conversation:export', async (_event, markdown: string, suggestedName: string) => {
    const result = await dialog.showSaveDialog({
      defaultPath: `${suggestedName.replace(/[<>:\"/\\|?*]/g, '-').slice(0, 80)}.md`,
      filters: [{ name: 'Markdown', extensions: ['md'] }, { name: 'Text', extensions: ['txt'] }],
    })
    if (result.canceled || !result.filePath) return false
    await fs.writeFile(result.filePath, markdown, 'utf8')
    return true
  })
  ipcMain.handle('workspace:select', async () => {
    const result = await dialog.showOpenDialog({ title: 'Choose a Skepo workspace', properties: ['openDirectory', 'createDirectory'] })
    return result.canceled ? undefined : result.filePaths[0]
  })
  ipcMain.handle('workspace:init', async (_event, workspace: string, bots: Bot[]) => {
    await initializeWorkspace(workspace, bots)
    await syncWorkspaceBots(workspace, bots)
    watchWorkspace(workspace, _event.sender)
    return workspaceStatus(workspace)
  })
  ipcMain.handle('workspace:sync-bots', async (_event, workspace: string, bots: Bot[]) => {
    await initializeWorkspace(workspace, bots)
    await syncWorkspaceBots(workspace, bots)
  })
  ipcMain.handle('workspace:status', async (event, workspace: string) => { const status = await workspaceStatus(workspace); if (status.initialized) watchWorkspace(workspace, event.sender); return status })
  ipcMain.handle('workspace:find-notes', (_event, workspace: string, query: string, botId: string, limit: number) => relevantNotes(workspace, query, botId, limit))
  ipcMain.handle('workspace:record-work', (_event, workspace: string, bot: Bot, conversationId: string, title: string, request: string, outcome: string) => recordWork(workspace, bot, conversationId, title, request, outcome))
  ipcMain.handle('workspace:record-handoff', (_event, workspace: string, requester: Bot, consultant: Bot, conversationId: string, task: string, response: string) => recordWork(workspace, consultant, conversationId, `Handoff: ${task}`, task, response, 'handoff', requester))
  ipcMain.handle('workspace:open', async (_event, workspace: string) => {
    const error = await shell.openPath(ledgerRoot(workspace))
    if (error) throw new Error(error)
  })
  ipcMain.handle('ollama:consult', async (_event, request: ConsultationRequest) => {
    const context = request.context.length ? `\n\nRelevant Shared Ledger cards:\n${request.context.map(note => `- ${note.botName} / ${note.title}: ${note.outcome}`).join('\n')}` : ''
    const response = await fetchOllama(`${cleanBaseUrl(request.ollamaUrl)}/api/chat`, {
      method: 'POST', headers: { 'Content-Type': 'application/json' }, signal: AbortSignal.timeout(180_000),
      body: JSON.stringify({
        model: request.consultant.model,
        stream: false,
        messages: [
          { role: 'system', content: `${request.consultant.systemPrompt}\n\nYou are consulting for another AI bot named ${request.requester.name}. Produce a compact handoff: state your conclusion, key evidence, risks, and exact next actions. Do not restate the whole task.` },
          { role: 'user', content: `${request.task}${context}` },
        ],
        options: { temperature: request.consultant.temperature, top_p: request.consultant.topP, num_ctx: request.consultant.contextLength },
      }),
    })
    if (!response.ok) throw new Error(await response.text() || `Ollama returned HTTP ${response.status}`)
    const data = await response.json() as { message?: { content?: string }; error?: string }
    if (data.error) throw new Error(data.error)
    return data.message?.content?.trim() ?? ''
  })
  ipcMain.handle('workflow:list', (_event, workspace: string) => listWorkflows(workspace))
  ipcMain.handle('workflow:start', async (event, request: WorkflowStartRequest) => {
    return startWorkflow(request, runModel, relevantNotes, createWorkflowEmitter(event.sender, request))
  })
  ipcMain.handle('workflow:approve', async (event, request: WorkflowStartRequest, sessionId: string) => {
    return approveWorkflow(request, sessionId, runModel, relevantNotes, createWorkflowEmitter(event.sender, request))
  })
  ipcMain.handle('workflow:pause', async (event, workspace: string, sessionId: string, paused: boolean) => {
    const emit = (manifest: unknown) => { if (!event.sender.isDestroyed()) event.sender.send('workflow:event', { type: 'updated', manifest }) }
    return setManifestPaused(workspace, sessionId, paused, emit)
  })
  ipcMain.handle('workflow:cancel', async (event, workspace: string, sessionId: string) => {
    const emit = (manifest: unknown) => { if (!event.sender.isDestroyed()) event.sender.send('workflow:event', { type: 'updated', manifest }) }
    return setManifestCancelled(workspace, sessionId, emit)
  })
  ipcMain.handle('workflow:retry-task', async (event, request: WorkflowStartRequest, sessionId: string, taskId: string) => {
    return retryWorkflowTask(request, sessionId, taskId, runModel, relevantNotes, createWorkflowEmitter(event.sender, request))
  })
  ipcMain.on('window:minimize', (event) => BrowserWindow.fromWebContents(event.sender)?.minimize())
  ipcMain.on('window:maximize', (event) => {
    const win = BrowserWindow.fromWebContents(event.sender)
    if (win?.isMaximized()) win.unmaximize(); else win?.maximize()
  })
  ipcMain.on('window:close', (event) => BrowserWindow.fromWebContents(event.sender)?.close())
}

function createWindow() {
  const capturePath = process.env.SKEPO_CAPTURE_PATH
  const win = new BrowserWindow({
    width: 1440,
    height: 920,
    minWidth: 980,
    minHeight: 650,
    frame: false,
    backgroundColor: '#09090b',
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  })
  if (capturePath) {
    win.webContents.once('did-finish-load', () => {
      win.showInactive()
      setTimeout(async () => {
        const image = await win.webContents.capturePage()
        await fs.mkdir(path.dirname(capturePath), { recursive: true })
        await fs.writeFile(capturePath, image.toPNG())
        app.quit()
      }, 3000)
    })
  } else win.once('ready-to-show', () => win.show())
  win.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:\/\//.test(url)) void shell.openExternal(url)
    return { action: 'deny' }
  })
  const devUrl = process.env.VITE_DEV_SERVER_URL
  if (devUrl) void win.loadURL(devUrl)
  else void win.loadFile(path.join(__dirname, '../../dist/index.html'))
}

app.whenReady().then(() => {
  registerIpc()
  createWindow()
  app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow() })
})
app.on('window-all-closed', () => { for (const watcher of workspaceWatchers.values()) watcher.close(); workspaceWatchers.clear(); if (process.platform !== 'darwin') app.quit() })
