import { BookOpen, BrainCircuit, CheckCircle2, ExternalLink, FolderOpen, KeyRound, RefreshCw, ServerOff, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { AppSettings, DecisionEngineStatus } from '../types'

export function SettingsView({ settings, status, decisionStatus, onSave, onTest, onChooseWorkspace, onSetJevKey, onClearJevKey }: { settings: AppSettings; status: { connected: boolean; version?: string; error?: string; checking: boolean }; decisionStatus: DecisionEngineStatus; onSave(settings: AppSettings): void; onTest(url: string): void; onChooseWorkspace(): Promise<string | undefined>; onSetJevKey(key: string): Promise<void>; onClearJevKey(): Promise<void> }) {
  const [draft, setDraft] = useState(settings)
  const [jevKey, setJevKey] = useState('')
  const [jevBusy, setJevBusy] = useState(false)
  useEffect(() => setDraft(settings), [settings])
  return <main className="page-view settings-page">
    <div className="page-heading"><div><span className="eyebrow">Preferences</span><h1>Settings</h1><p>Configure your local connection and workspace behavior.</p></div></div>
    <section className="settings-section"><h2>Ollama connection</h2><p>Skepo talks directly to Ollama's HTTP API.</p><label>Server URL<div className="inline-field"><input value={draft.ollamaUrl} onChange={e => setDraft({ ...draft, ollamaUrl: e.target.value })} /><button className="secondary" onClick={() => onTest(draft.ollamaUrl)} disabled={status.checking}><RefreshCw size={16} className={status.checking ? 'spinning' : ''} />Test</button></div></label><div className={`inline-status ${status.connected ? 'success' : 'error'}`}>{status.connected ? <CheckCircle2 size={16} /> : <ServerOff size={16} />}<span>{status.connected ? `Connected${status.version ? ` to Ollama ${status.version}` : ''}` : status.error ?? 'Not connected'}</span></div></section>
    <section className="settings-section memory-settings"><div className="section-title-icon"><BookOpen size={18} /><div><h2>Shared Ledger</h2><p>File-native memory and handoffs between bots.</p></div></div><label>Workspace folder<div className="inline-field"><input value={draft.workspacePath} readOnly placeholder="Choose a folder on any local drive" /><button className="secondary" onClick={async () => { const selected = await onChooseWorkspace(); if (selected) setDraft({ ...draft, workspacePath: selected }) }}><FolderOpen size={16} />Browse</button></div></label><Toggle label="Share relevant work cards" description="Add a small set of locally selected Markdown notes to new requests." checked={draft.sharedMemoryEnabled} onChange={sharedMemoryEnabled => setDraft({ ...draft, sharedMemoryEnabled })} /><label>Maximum cards per request<select value={draft.maxSharedNotes} onChange={e => setDraft({ ...draft, maxSharedNotes: Number(e.target.value) })}>{[1,2,3,4,5,6,8].map(count => <option key={count} value={count}>{count} card{count === 1 ? '' : 's'}</option>)}</select><span className="field-help">A lower number saves context tokens. Four is a balanced default.</span></label></section>
    <section className="settings-section decision-settings"><div className="section-title-icon"><BrainCircuit size={18} /><div><h2>Decision engine</h2><p>Fast typed gates for plans and worker results.</p></div></div><label>Mode<select value={draft.decisionMode} onChange={e => setDraft({ ...draft, decisionMode: e.target.value as AppSettings['decisionMode'] })}><option value="auto">Auto · Jev when configured, local fallback</option><option value="local">Local only · zero network and zero decision tokens</option><option value="jev">Prefer Jev · fall back safely if unavailable</option></select><span className="field-help">Jev makes bounded choices; Ollama still performs planning, building, and review.</span></label><div className={`inline-status ${decisionStatus.configured ? 'success' : ''}`}><KeyRound size={16} /><span>{decisionStatus.configured ? `${decisionStatus.model} configured with Windows-encrypted credentials` : 'No Jev key yet — Skepo works immediately with deterministic local gates'}</span></div><label>TypeSafe API key<div className="inline-field"><input type="password" value={jevKey} autoComplete="off" placeholder={decisionStatus.configured ? 'Enter a replacement key' : 'Paste a key to enable Jev'} onChange={e => setJevKey(e.target.value)} /><button className="secondary" disabled={!jevKey.trim() || jevBusy || !decisionStatus.encryptionAvailable} onClick={async () => { setJevBusy(true); try { await onSetJevKey(jevKey); setJevKey('') } catch { /* The parent displays the error. */ } finally { setJevBusy(false) } }}><KeyRound size={15} />{jevBusy ? 'Saving…' : 'Save key'}</button>{decisionStatus.configured && <button className="secondary danger" disabled={jevBusy} onClick={async () => { setJevBusy(true); try { await onClearJevKey() } catch { /* The parent displays the error. */ } finally { setJevBusy(false) } }}><Trash2 size={15} />Remove</button>}</div><span className="field-help">When Jev runs, the current plan or task result is sent to TypeSafe AI. The key is never stored in the workspace or Git.</span></label></section>
    <section className="settings-section"><h2>Appearance</h2><div className="segmented" role="group" aria-label="Theme">{(['dark','light','system'] as const).map(theme => <button className={draft.theme === theme ? 'active' : ''} key={theme} onClick={() => setDraft({ ...draft, theme })}>{theme[0].toUpperCase() + theme.slice(1)}</button>)}</div><Toggle label="Compact conversation list" description="Fit more items in the sidebar." checked={draft.compactMode} onChange={compactMode => setDraft({ ...draft, compactMode })} /></section>
    <section className="settings-section"><h2>Chat</h2><Toggle label="Send with Enter" description="Use Shift + Enter for a new line. When off, use Ctrl + Enter to send." checked={draft.sendOnEnter} onChange={sendOnEnter => setDraft({ ...draft, sendOnEnter })} /></section>
    <section className="settings-section about"><h2>About Skepo</h2><p>Version 0.5.0 · Your agent profiles and chat history are stored locally in your Windows app data folder.</p><a href="https://ollama.com/library" target="_blank" rel="noreferrer">Browse the Ollama model library<ExternalLink size={14} /></a></section>
    <div className="settings-save"><button className="primary" onClick={() => onSave(draft)}>Save settings</button></div>
  </main>
}

function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange(value: boolean): void }) {
  return <label className="toggle-row"><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /><i aria-hidden="true" /></label>
}
